import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";
import StoryblokProvider from "./components/StoryblokProvider";

const titillium = Titillium_Web({
  subsets: ["latin"],
  weight: ["400","600","700"],
  variable: "--font-titillium",
});

export const metadata: Metadata = {
  title: "Assignment-2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
    <html lang="en">
      <body
        className={`${titillium.variable}`}
      >
        {children}
      </body>
    </html>
    </StoryblokProvider>
  );
}
