import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { storyblokInit,apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import {Tour} from '../components/Tour';
import {Page} from '../components/Page';
import {Hero} from '../components/Hero';
import {Grid} from '../components/Grid';
import {Feature} from '../components/Feature';
import {Testimonial} from '../components/Testimonial';
import {RecommendedTours} from '../components/RecommendedTours';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken:process.env.STORYBLOK_TOKEN,
  use:[apiPlugin],
  components: {
      tour: Tour,
      page: Page,
      hero: Hero,
      grid: Grid,
      feature: Feature,
      testimonial: Testimonial,
      recommended_tours: RecommendedTours,
    },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>Wecome to Haptiq</div>
        {children}
      </body>
    </html>
      
    </StoryblokProvider>
    
  );
}
