import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { storyblokInit,apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import {Tour} from '../components/Tour';
import {Page} from '../components/Page';
import {Hero} from '../components/Hero';
import {Grid} from '../components/Grid';
import {Feature} from '../components/Feature';
import {Testimonial} from '../components/Testimonial';
import {RecommendedTours} from '../components/RecommendedTours';
import Link from "next/link";


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Tech-Tour",
  description: "Generated by create next app",
};

const cachedFetch=(input:any,init?:any):Promise<Response> =>{
  return fetch(input,{
    ...init,
    cache:"no-store",
  });
};



storyblokInit({
  accessToken:process.env.STORYBLOK_TOKEN,
  use:[apiPlugin],
  apiOptions:{
    fetch:cachedFetch,
  },
  components: {
      tour: Tour,
      page: Page,
      hero: Hero,
      grid: Grid,
      feature: Feature,
      testimonial: Testimonial,
      recommended_tours: RecommendedTours,
    },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
      <body className={`${inter.className} bg-blue-50`}>
        <header>
          <nav className="container mx-auto px-4 w-full py-8 flex justify-between">
            <Link href={"/"}>Home</Link>
            <Link href={"/tours"}>Tours</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
      
    </StoryblokProvider>
    
  );
}
